apiVersion: v1
kind: Service
metadata:
  name: profile
  labels:
    app.kubernetes.io/name: profile
    app.kubernetes.io/component: profile
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
    - port: 5012
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    app.kubernetes.io/name: profile
