apiVersion: v1
kind: Service
metadata:
  name: matching
  labels:
    app.kubernetes.io/name: matching
    app.kubernetes.io/component: matching
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: matching
