apiVersion: v1
kind: Service
metadata:
  name: jobs
  labels:
    app.kubernetes.io/name: jobs
    app.kubernetes.io/component: jobs
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
    - port: 5013
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    app.kubernetes.io/name: jobs
